/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BackupGitSpecificationApplyConfiguration represents an declarative configuration of the BackupGitSpecification type for use
// with apply.
type BackupGitSpecificationApplyConfiguration struct {
	BackupGitRepo        *string `json:"backupGitRepo,omitempty"`
	BackupGitSecretName  *string `json:"backupGitSecretName,omitempty"`
	BackupResponsability *string `json:"backupResponsability,omitempty"`
}

// BackupGitSpecificationApplyConfiguration constructs an declarative configuration of the BackupGitSpecification type for use with
// apply.
func BackupGitSpecification() *BackupGitSpecificationApplyConfiguration {
	return &BackupGitSpecificationApplyConfiguration{}
}

// WithBackupGitRepo sets the BackupGitRepo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupGitRepo field is set to the value of the last call.
func (b *BackupGitSpecificationApplyConfiguration) WithBackupGitRepo(value string) *BackupGitSpecificationApplyConfiguration {
	b.BackupGitRepo = &value
	return b
}

// WithBackupGitSecretName sets the BackupGitSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupGitSecretName field is set to the value of the last call.
func (b *BackupGitSpecificationApplyConfiguration) WithBackupGitSecretName(value string) *BackupGitSpecificationApplyConfiguration {
	b.BackupGitSecretName = &value
	return b
}

// WithBackupResponsability sets the BackupResponsability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupResponsability field is set to the value of the last call.
func (b *BackupGitSpecificationApplyConfiguration) WithBackupResponsability(value string) *BackupGitSpecificationApplyConfiguration {
	b.BackupResponsability = &value
	return b
}
