/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DetailSpecApplyConfiguration represents an declarative configuration of the DetailSpec type for use
// with apply.
type DetailSpecApplyConfiguration struct {
	Name        *string                    `json:"name,omitempty"`
	Description *string                    `json:"description,omitempty"`
	DistTags    *DistTagApplyConfiguration `json:"dist-tags,omitempty"`
	Versions    []string                   `json:"versions,omitempty"`
	Thumbnail   *string                    `json:"thumbnail,omitempty"`
}

// DetailSpecApplyConfiguration constructs an declarative configuration of the DetailSpec type for use with
// apply.
func DetailSpec() *DetailSpecApplyConfiguration {
	return &DetailSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DetailSpecApplyConfiguration) WithName(value string) *DetailSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DetailSpecApplyConfiguration) WithDescription(value string) *DetailSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithDistTags sets the DistTags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DistTags field is set to the value of the last call.
func (b *DetailSpecApplyConfiguration) WithDistTags(value *DistTagApplyConfiguration) *DetailSpecApplyConfiguration {
	b.DistTags = value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *DetailSpecApplyConfiguration) WithVersions(values ...string) *DetailSpecApplyConfiguration {
	for i := range values {
		b.Versions = append(b.Versions, values[i])
	}
	return b
}

// WithThumbnail sets the Thumbnail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thumbnail field is set to the value of the last call.
func (b *DetailSpecApplyConfiguration) WithThumbnail(value string) *DetailSpecApplyConfiguration {
	b.Thumbnail = &value
	return b
}
