/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// EntandoPluginSpecApplyConfiguration represents an declarative configuration of the EntandoPluginSpec type for use
// with apply.
type EntandoPluginSpecApplyConfiguration struct {
	TenantCode           *string                                `json:"tenantCode,omitempty"`
	Image                *string                                `json:"spec,omitempty"`
	Replicas             *int                                   `json:"replicas,omitempty"`
	Dbms                 *string                                `json:"dbms,omitempty"`
	StorageClass         *string                                `json:"storageClass,omitempty"`
	IngressHostName      *string                                `json:"ingressHostName,omitempty"`
	IngressPath          *string                                `json:"ingressPath,omitempty"`
	TlsSecretName        *string                                `json:"tlsSecretName,omitempty"`
	ServiceAccountToUse  *string                                `json:"tlsSecretName,omitempty"`
	EnvironmentVariables []v1.EnvVar                            `json:"environmentVariables,omitempty"`
	ResourceRequirements *ResourceRequirementApplyConfiguration `json:"resourceRequirements,omitempty"`
	KeycloakToUse        *KeycloakSpecApplyConfiguration        `json:"keycloakToUse,omitempty"`
	HealthCheckPath      *string                                `json:"healthCheckPath,omitempty"`
	SecurityLevel        *string                                `json:"securityLevel,omitempty"`
	ConnectionConfigName *string                                `json:"connectionConfigNames,omitempty"`
	CompanionContainers  []string                               `json:"companionContainers,omitempty"`
	Roles                []RoleApplyConfiguration               `json:"roles,omitempty"`
	Permissions          []PermissionApplyConfiguration         `json:"permissions,omitempty"`
}

// EntandoPluginSpecApplyConfiguration constructs an declarative configuration of the EntandoPluginSpec type for use with
// apply.
func EntandoPluginSpec() *EntandoPluginSpecApplyConfiguration {
	return &EntandoPluginSpecApplyConfiguration{}
}

// WithTenantCode sets the TenantCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantCode field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithTenantCode(value string) *EntandoPluginSpecApplyConfiguration {
	b.TenantCode = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithImage(value string) *EntandoPluginSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithReplicas(value int) *EntandoPluginSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithDbms sets the Dbms field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dbms field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithDbms(value string) *EntandoPluginSpecApplyConfiguration {
	b.Dbms = &value
	return b
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithStorageClass(value string) *EntandoPluginSpecApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithIngressHostName sets the IngressHostName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressHostName field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithIngressHostName(value string) *EntandoPluginSpecApplyConfiguration {
	b.IngressHostName = &value
	return b
}

// WithIngressPath sets the IngressPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressPath field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithIngressPath(value string) *EntandoPluginSpecApplyConfiguration {
	b.IngressPath = &value
	return b
}

// WithTlsSecretName sets the TlsSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TlsSecretName field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithTlsSecretName(value string) *EntandoPluginSpecApplyConfiguration {
	b.TlsSecretName = &value
	return b
}

// WithServiceAccountToUse sets the ServiceAccountToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountToUse field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithServiceAccountToUse(value string) *EntandoPluginSpecApplyConfiguration {
	b.ServiceAccountToUse = &value
	return b
}

// WithEnvironmentVariables adds the given value to the EnvironmentVariables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EnvironmentVariables field.
func (b *EntandoPluginSpecApplyConfiguration) WithEnvironmentVariables(values ...v1.EnvVar) *EntandoPluginSpecApplyConfiguration {
	for i := range values {
		b.EnvironmentVariables = append(b.EnvironmentVariables, values[i])
	}
	return b
}

// WithResourceRequirements sets the ResourceRequirements field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceRequirements field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithResourceRequirements(value *ResourceRequirementApplyConfiguration) *EntandoPluginSpecApplyConfiguration {
	b.ResourceRequirements = value
	return b
}

// WithKeycloakToUse sets the KeycloakToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeycloakToUse field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithKeycloakToUse(value *KeycloakSpecApplyConfiguration) *EntandoPluginSpecApplyConfiguration {
	b.KeycloakToUse = value
	return b
}

// WithHealthCheckPath sets the HealthCheckPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthCheckPath field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithHealthCheckPath(value string) *EntandoPluginSpecApplyConfiguration {
	b.HealthCheckPath = &value
	return b
}

// WithSecurityLevel sets the SecurityLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityLevel field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithSecurityLevel(value string) *EntandoPluginSpecApplyConfiguration {
	b.SecurityLevel = &value
	return b
}

// WithConnectionConfigName sets the ConnectionConfigName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionConfigName field is set to the value of the last call.
func (b *EntandoPluginSpecApplyConfiguration) WithConnectionConfigName(value string) *EntandoPluginSpecApplyConfiguration {
	b.ConnectionConfigName = &value
	return b
}

// WithCompanionContainers adds the given value to the CompanionContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CompanionContainers field.
func (b *EntandoPluginSpecApplyConfiguration) WithCompanionContainers(values ...string) *EntandoPluginSpecApplyConfiguration {
	for i := range values {
		b.CompanionContainers = append(b.CompanionContainers, values[i])
	}
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *EntandoPluginSpecApplyConfiguration) WithRoles(values ...*RoleApplyConfiguration) *EntandoPluginSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoles")
		}
		b.Roles = append(b.Roles, *values[i])
	}
	return b
}

// WithPermissions adds the given value to the Permissions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Permissions field.
func (b *EntandoPluginSpecApplyConfiguration) WithPermissions(values ...*PermissionApplyConfiguration) *EntandoPluginSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPermissions")
		}
		b.Permissions = append(b.Permissions, *values[i])
	}
	return b
}
