/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ExternallyProvidedServiceSpecApplyConfiguration represents an declarative configuration of the ExternallyProvidedServiceSpec type for use
// with apply.
type ExternallyProvidedServiceSpecApplyConfiguration struct {
	Host            *string `json:"host,omitempty"`
	Port            *string `json:"port,omitempty"`
	AdminSecretName *string `json:"adminSecretName,omitempty"`
}

// ExternallyProvidedServiceSpecApplyConfiguration constructs an declarative configuration of the ExternallyProvidedServiceSpec type for use with
// apply.
func ExternallyProvidedServiceSpec() *ExternallyProvidedServiceSpecApplyConfiguration {
	return &ExternallyProvidedServiceSpecApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *ExternallyProvidedServiceSpecApplyConfiguration) WithHost(value string) *ExternallyProvidedServiceSpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ExternallyProvidedServiceSpecApplyConfiguration) WithPort(value string) *ExternallyProvidedServiceSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithAdminSecretName sets the AdminSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminSecretName field is set to the value of the last call.
func (b *ExternallyProvidedServiceSpecApplyConfiguration) WithAdminSecretName(value string) *ExternallyProvidedServiceSpecApplyConfiguration {
	b.AdminSecretName = &value
	return b
}
