/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ProvidedCapabilityStatusApplyConfiguration represents an declarative configuration of the ProvidedCapabilityStatus type for use
// with apply.
type ProvidedCapabilityStatusApplyConfiguration struct {
	Phase *string `json:"phase,omitempty"`
}

// ProvidedCapabilityStatusApplyConfiguration constructs an declarative configuration of the ProvidedCapabilityStatus type for use with
// apply.
func ProvidedCapabilityStatus() *ProvidedCapabilityStatusApplyConfiguration {
	return &ProvidedCapabilityStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ProvidedCapabilityStatusApplyConfiguration) WithPhase(value string) *ProvidedCapabilityStatusApplyConfiguration {
	b.Phase = &value
	return b
}
