/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	scheme "github.com/antromeo/entando-clients/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EntandoAppsGetter has a method to return a EntandoAppInterface.
// A group's client should implement this interface.
type EntandoAppsGetter interface {
	EntandoApps(namespace string) EntandoAppInterface
}

// EntandoAppInterface has methods to work with EntandoApp resources.
type EntandoAppInterface interface {
	Create(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.CreateOptions) (*v1.EntandoApp, error)
	Update(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (*v1.EntandoApp, error)
	UpdateStatus(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (*v1.EntandoApp, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EntandoApp, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EntandoAppList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoApp, err error)
	Apply(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error)
	ApplyStatus(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error)
	EntandoAppExpansion
}

// entandoApps implements EntandoAppInterface
type entandoApps struct {
	client rest.Interface
	ns     string
}

// newEntandoApps returns a EntandoApps
func newEntandoApps(c *EntandoV1Client, namespace string) *entandoApps {
	return &entandoApps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the entandoApp, and returns the corresponding entandoApp object, and an error if there is any.
func (c *entandoApps) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoApp, err error) {
	result = &v1.EntandoApp{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("entandoapps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EntandoApps that match those selectors.
func (c *entandoApps) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoAppList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EntandoAppList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("entandoapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested entandoApps.
func (c *entandoApps) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("entandoapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a entandoApp and creates it.  Returns the server's representation of the entandoApp, and an error, if there is any.
func (c *entandoApps) Create(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.CreateOptions) (result *v1.EntandoApp, err error) {
	result = &v1.EntandoApp{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("entandoapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoApp).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a entandoApp and updates it. Returns the server's representation of the entandoApp, and an error, if there is any.
func (c *entandoApps) Update(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (result *v1.EntandoApp, err error) {
	result = &v1.EntandoApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("entandoapps").
		Name(entandoApp.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoApp).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *entandoApps) UpdateStatus(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (result *v1.EntandoApp, err error) {
	result = &v1.EntandoApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("entandoapps").
		Name(entandoApp.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoApp).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the entandoApp and deletes it. Returns an error if one occurs.
func (c *entandoApps) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("entandoapps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *entandoApps) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("entandoapps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched entandoApp.
func (c *entandoApps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoApp, err error) {
	result = &v1.EntandoApp{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("entandoapps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoApp.
func (c *entandoApps) Apply(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error) {
	if entandoApp == nil {
		return nil, fmt.Errorf("entandoApp provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(entandoApp)
	if err != nil {
		return nil, err
	}
	name := entandoApp.Name
	if name == nil {
		return nil, fmt.Errorf("entandoApp.Name must be provided to Apply")
	}
	result = &v1.EntandoApp{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("entandoapps").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *entandoApps) ApplyStatus(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error) {
	if entandoApp == nil {
		return nil, fmt.Errorf("entandoApp provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(entandoApp)
	if err != nil {
		return nil, err
	}

	name := entandoApp.Name
	if name == nil {
		return nil, fmt.Errorf("entandoApp.Name must be provided to Apply")
	}

	result = &v1.EntandoApp{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("entandoapps").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
