/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	scheme "github.com/antromeo/entando-clients/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EntandoPluginsGetter has a method to return a EntandoPluginInterface.
// A group's client should implement this interface.
type EntandoPluginsGetter interface {
	EntandoPlugins(namespace string) EntandoPluginInterface
}

// EntandoPluginInterface has methods to work with EntandoPlugin resources.
type EntandoPluginInterface interface {
	Create(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.CreateOptions) (*v1.EntandoPlugin, error)
	Update(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (*v1.EntandoPlugin, error)
	UpdateStatus(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (*v1.EntandoPlugin, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EntandoPlugin, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EntandoPluginList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoPlugin, err error)
	Apply(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error)
	ApplyStatus(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error)
	EntandoPluginExpansion
}

// entandoPlugins implements EntandoPluginInterface
type entandoPlugins struct {
	client rest.Interface
	ns     string
}

// newEntandoPlugins returns a EntandoPlugins
func newEntandoPlugins(c *EntandoV1Client, namespace string) *entandoPlugins {
	return &entandoPlugins{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the entandoPlugin, and returns the corresponding entandoPlugin object, and an error if there is any.
func (c *entandoPlugins) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoPlugin, err error) {
	result = &v1.EntandoPlugin{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EntandoPlugins that match those selectors.
func (c *entandoPlugins) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoPluginList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EntandoPluginList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("entandoplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested entandoPlugins.
func (c *entandoPlugins) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("entandoplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a entandoPlugin and creates it.  Returns the server's representation of the entandoPlugin, and an error, if there is any.
func (c *entandoPlugins) Create(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.CreateOptions) (result *v1.EntandoPlugin, err error) {
	result = &v1.EntandoPlugin{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("entandoplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoPlugin).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a entandoPlugin and updates it. Returns the server's representation of the entandoPlugin, and an error, if there is any.
func (c *entandoPlugins) Update(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (result *v1.EntandoPlugin, err error) {
	result = &v1.EntandoPlugin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(entandoPlugin.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoPlugin).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *entandoPlugins) UpdateStatus(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (result *v1.EntandoPlugin, err error) {
	result = &v1.EntandoPlugin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(entandoPlugin.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(entandoPlugin).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the entandoPlugin and deletes it. Returns an error if one occurs.
func (c *entandoPlugins) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *entandoPlugins) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("entandoplugins").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched entandoPlugin.
func (c *entandoPlugins) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoPlugin, err error) {
	result = &v1.EntandoPlugin{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoPlugin.
func (c *entandoPlugins) Apply(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error) {
	if entandoPlugin == nil {
		return nil, fmt.Errorf("entandoPlugin provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(entandoPlugin)
	if err != nil {
		return nil, err
	}
	name := entandoPlugin.Name
	if name == nil {
		return nil, fmt.Errorf("entandoPlugin.Name must be provided to Apply")
	}
	result = &v1.EntandoPlugin{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *entandoPlugins) ApplyStatus(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error) {
	if entandoPlugin == nil {
		return nil, fmt.Errorf("entandoPlugin provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(entandoPlugin)
	if err != nil {
		return nil, err
	}

	name := entandoPlugin.Name
	if name == nil {
		return nil, fmt.Errorf("entandoPlugin.Name must be provided to Apply")
	}

	result = &v1.EntandoPlugin{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("entandoplugins").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
