/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEntandoApps implements EntandoAppInterface
type FakeEntandoApps struct {
	Fake *FakeEntandoV1
	ns   string
}

var entandoappsResource = v1.SchemeGroupVersion.WithResource("entandoapps")

var entandoappsKind = v1.SchemeGroupVersion.WithKind("EntandoApp")

// Get takes name of the entandoApp, and returns the corresponding entandoApp object, and an error if there is any.
func (c *FakeEntandoApps) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(entandoappsResource, c.ns, name), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// List takes label and field selectors, and returns the list of EntandoApps that match those selectors.
func (c *FakeEntandoApps) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoAppList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(entandoappsResource, entandoappsKind, c.ns, opts), &v1.EntandoAppList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EntandoAppList{ListMeta: obj.(*v1.EntandoAppList).ListMeta}
	for _, item := range obj.(*v1.EntandoAppList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested entandoApps.
func (c *FakeEntandoApps) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(entandoappsResource, c.ns, opts))

}

// Create takes the representation of a entandoApp and creates it.  Returns the server's representation of the entandoApp, and an error, if there is any.
func (c *FakeEntandoApps) Create(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.CreateOptions) (result *v1.EntandoApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(entandoappsResource, c.ns, entandoApp), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// Update takes the representation of a entandoApp and updates it. Returns the server's representation of the entandoApp, and an error, if there is any.
func (c *FakeEntandoApps) Update(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (result *v1.EntandoApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(entandoappsResource, c.ns, entandoApp), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEntandoApps) UpdateStatus(ctx context.Context, entandoApp *v1.EntandoApp, opts metav1.UpdateOptions) (*v1.EntandoApp, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(entandoappsResource, "status", c.ns, entandoApp), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// Delete takes name of the entandoApp and deletes it. Returns an error if one occurs.
func (c *FakeEntandoApps) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(entandoappsResource, c.ns, name, opts), &v1.EntandoApp{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEntandoApps) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(entandoappsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EntandoAppList{})
	return err
}

// Patch applies the patch and returns the patched entandoApp.
func (c *FakeEntandoApps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoappsResource, c.ns, name, pt, data, subresources...), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoApp.
func (c *FakeEntandoApps) Apply(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error) {
	if entandoApp == nil {
		return nil, fmt.Errorf("entandoApp provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoApp)
	if err != nil {
		return nil, err
	}
	name := entandoApp.Name
	if name == nil {
		return nil, fmt.Errorf("entandoApp.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoappsResource, c.ns, *name, types.ApplyPatchType, data), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeEntandoApps) ApplyStatus(ctx context.Context, entandoApp *entandoorgv1.EntandoAppApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoApp, err error) {
	if entandoApp == nil {
		return nil, fmt.Errorf("entandoApp provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoApp)
	if err != nil {
		return nil, err
	}
	name := entandoApp.Name
	if name == nil {
		return nil, fmt.Errorf("entandoApp.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoappsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.EntandoApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoApp), err
}
