/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEntandoAppPluginLinks implements EntandoAppPluginLinkInterface
type FakeEntandoAppPluginLinks struct {
	Fake *FakeEntandoV1
	ns   string
}

var entandoapppluginlinksResource = v1.SchemeGroupVersion.WithResource("entandoapppluginlinks")

var entandoapppluginlinksKind = v1.SchemeGroupVersion.WithKind("EntandoAppPluginLink")

// Get takes name of the entandoAppPluginLink, and returns the corresponding entandoAppPluginLink object, and an error if there is any.
func (c *FakeEntandoAppPluginLinks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoAppPluginLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(entandoapppluginlinksResource, c.ns, name), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// List takes label and field selectors, and returns the list of EntandoAppPluginLinks that match those selectors.
func (c *FakeEntandoAppPluginLinks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoAppPluginLinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(entandoapppluginlinksResource, entandoapppluginlinksKind, c.ns, opts), &v1.EntandoAppPluginLinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EntandoAppPluginLinkList{ListMeta: obj.(*v1.EntandoAppPluginLinkList).ListMeta}
	for _, item := range obj.(*v1.EntandoAppPluginLinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested entandoAppPluginLinks.
func (c *FakeEntandoAppPluginLinks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(entandoapppluginlinksResource, c.ns, opts))

}

// Create takes the representation of a entandoAppPluginLink and creates it.  Returns the server's representation of the entandoAppPluginLink, and an error, if there is any.
func (c *FakeEntandoAppPluginLinks) Create(ctx context.Context, entandoAppPluginLink *v1.EntandoAppPluginLink, opts metav1.CreateOptions) (result *v1.EntandoAppPluginLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(entandoapppluginlinksResource, c.ns, entandoAppPluginLink), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// Update takes the representation of a entandoAppPluginLink and updates it. Returns the server's representation of the entandoAppPluginLink, and an error, if there is any.
func (c *FakeEntandoAppPluginLinks) Update(ctx context.Context, entandoAppPluginLink *v1.EntandoAppPluginLink, opts metav1.UpdateOptions) (result *v1.EntandoAppPluginLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(entandoapppluginlinksResource, c.ns, entandoAppPluginLink), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEntandoAppPluginLinks) UpdateStatus(ctx context.Context, entandoAppPluginLink *v1.EntandoAppPluginLink, opts metav1.UpdateOptions) (*v1.EntandoAppPluginLink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(entandoapppluginlinksResource, "status", c.ns, entandoAppPluginLink), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// Delete takes name of the entandoAppPluginLink and deletes it. Returns an error if one occurs.
func (c *FakeEntandoAppPluginLinks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(entandoapppluginlinksResource, c.ns, name, opts), &v1.EntandoAppPluginLink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEntandoAppPluginLinks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(entandoapppluginlinksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EntandoAppPluginLinkList{})
	return err
}

// Patch applies the patch and returns the patched entandoAppPluginLink.
func (c *FakeEntandoAppPluginLinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoAppPluginLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoapppluginlinksResource, c.ns, name, pt, data, subresources...), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoAppPluginLink.
func (c *FakeEntandoAppPluginLinks) Apply(ctx context.Context, entandoAppPluginLink *entandoorgv1.EntandoAppPluginLinkApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoAppPluginLink, err error) {
	if entandoAppPluginLink == nil {
		return nil, fmt.Errorf("entandoAppPluginLink provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoAppPluginLink)
	if err != nil {
		return nil, err
	}
	name := entandoAppPluginLink.Name
	if name == nil {
		return nil, fmt.Errorf("entandoAppPluginLink.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoapppluginlinksResource, c.ns, *name, types.ApplyPatchType, data), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeEntandoAppPluginLinks) ApplyStatus(ctx context.Context, entandoAppPluginLink *entandoorgv1.EntandoAppPluginLinkApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoAppPluginLink, err error) {
	if entandoAppPluginLink == nil {
		return nil, fmt.Errorf("entandoAppPluginLink provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoAppPluginLink)
	if err != nil {
		return nil, err
	}
	name := entandoAppPluginLink.Name
	if name == nil {
		return nil, fmt.Errorf("entandoAppPluginLink.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandoapppluginlinksResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.EntandoAppPluginLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoAppPluginLink), err
}
