/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvidedCapabilities implements ProvidedCapabilityInterface
type FakeProvidedCapabilities struct {
	Fake *FakeEntandoV1
	ns   string
}

var providedcapabilitiesResource = v1.SchemeGroupVersion.WithResource("providedcapabilities")

var providedcapabilitiesKind = v1.SchemeGroupVersion.WithKind("ProvidedCapability")

// Get takes name of the providedCapability, and returns the corresponding providedCapability object, and an error if there is any.
func (c *FakeProvidedCapabilities) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ProvidedCapability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(providedcapabilitiesResource, c.ns, name), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// List takes label and field selectors, and returns the list of ProvidedCapabilities that match those selectors.
func (c *FakeProvidedCapabilities) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ProvidedCapabilityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(providedcapabilitiesResource, providedcapabilitiesKind, c.ns, opts), &v1.ProvidedCapabilityList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ProvidedCapabilityList{ListMeta: obj.(*v1.ProvidedCapabilityList).ListMeta}
	for _, item := range obj.(*v1.ProvidedCapabilityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providedCapabilities.
func (c *FakeProvidedCapabilities) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(providedcapabilitiesResource, c.ns, opts))

}

// Create takes the representation of a providedCapability and creates it.  Returns the server's representation of the providedCapability, and an error, if there is any.
func (c *FakeProvidedCapabilities) Create(ctx context.Context, providedCapability *v1.ProvidedCapability, opts metav1.CreateOptions) (result *v1.ProvidedCapability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(providedcapabilitiesResource, c.ns, providedCapability), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// Update takes the representation of a providedCapability and updates it. Returns the server's representation of the providedCapability, and an error, if there is any.
func (c *FakeProvidedCapabilities) Update(ctx context.Context, providedCapability *v1.ProvidedCapability, opts metav1.UpdateOptions) (result *v1.ProvidedCapability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(providedcapabilitiesResource, c.ns, providedCapability), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvidedCapabilities) UpdateStatus(ctx context.Context, providedCapability *v1.ProvidedCapability, opts metav1.UpdateOptions) (*v1.ProvidedCapability, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(providedcapabilitiesResource, "status", c.ns, providedCapability), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// Delete takes name of the providedCapability and deletes it. Returns an error if one occurs.
func (c *FakeProvidedCapabilities) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(providedcapabilitiesResource, c.ns, name, opts), &v1.ProvidedCapability{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvidedCapabilities) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(providedcapabilitiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ProvidedCapabilityList{})
	return err
}

// Patch applies the patch and returns the patched providedCapability.
func (c *FakeProvidedCapabilities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ProvidedCapability, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providedcapabilitiesResource, c.ns, name, pt, data, subresources...), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied providedCapability.
func (c *FakeProvidedCapabilities) Apply(ctx context.Context, providedCapability *entandoorgv1.ProvidedCapabilityApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ProvidedCapability, err error) {
	if providedCapability == nil {
		return nil, fmt.Errorf("providedCapability provided to Apply must not be nil")
	}
	data, err := json.Marshal(providedCapability)
	if err != nil {
		return nil, err
	}
	name := providedCapability.Name
	if name == nil {
		return nil, fmt.Errorf("providedCapability.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providedcapabilitiesResource, c.ns, *name, types.ApplyPatchType, data), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeProvidedCapabilities) ApplyStatus(ctx context.Context, providedCapability *entandoorgv1.ProvidedCapabilityApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ProvidedCapability, err error) {
	if providedCapability == nil {
		return nil, fmt.Errorf("providedCapability provided to Apply must not be nil")
	}
	data, err := json.Marshal(providedCapability)
	if err != nil {
		return nil, err
	}
	name := providedCapability.Name
	if name == nil {
		return nil, fmt.Errorf("providedCapability.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providedcapabilitiesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.ProvidedCapability{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ProvidedCapability), err
}
