/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEntandoPlugins implements EntandoPluginInterface
type FakeEntandoPlugins struct {
	Fake *FakeEntandoV1
	ns   string
}

var entandopluginsResource = v1.SchemeGroupVersion.WithResource("entandoplugins")

var entandopluginsKind = v1.SchemeGroupVersion.WithKind("EntandoPlugin")

// Get takes name of the entandoPlugin, and returns the corresponding entandoPlugin object, and an error if there is any.
func (c *FakeEntandoPlugins) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(entandopluginsResource, c.ns, name), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// List takes label and field selectors, and returns the list of EntandoPlugins that match those selectors.
func (c *FakeEntandoPlugins) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoPluginList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(entandopluginsResource, entandopluginsKind, c.ns, opts), &v1.EntandoPluginList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EntandoPluginList{ListMeta: obj.(*v1.EntandoPluginList).ListMeta}
	for _, item := range obj.(*v1.EntandoPluginList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested entandoPlugins.
func (c *FakeEntandoPlugins) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(entandopluginsResource, c.ns, opts))

}

// Create takes the representation of a entandoPlugin and creates it.  Returns the server's representation of the entandoPlugin, and an error, if there is any.
func (c *FakeEntandoPlugins) Create(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.CreateOptions) (result *v1.EntandoPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(entandopluginsResource, c.ns, entandoPlugin), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// Update takes the representation of a entandoPlugin and updates it. Returns the server's representation of the entandoPlugin, and an error, if there is any.
func (c *FakeEntandoPlugins) Update(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (result *v1.EntandoPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(entandopluginsResource, c.ns, entandoPlugin), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEntandoPlugins) UpdateStatus(ctx context.Context, entandoPlugin *v1.EntandoPlugin, opts metav1.UpdateOptions) (*v1.EntandoPlugin, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(entandopluginsResource, "status", c.ns, entandoPlugin), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// Delete takes name of the entandoPlugin and deletes it. Returns an error if one occurs.
func (c *FakeEntandoPlugins) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(entandopluginsResource, c.ns, name, opts), &v1.EntandoPlugin{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEntandoPlugins) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(entandopluginsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EntandoPluginList{})
	return err
}

// Patch applies the patch and returns the patched entandoPlugin.
func (c *FakeEntandoPlugins) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandopluginsResource, c.ns, name, pt, data, subresources...), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoPlugin.
func (c *FakeEntandoPlugins) Apply(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error) {
	if entandoPlugin == nil {
		return nil, fmt.Errorf("entandoPlugin provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoPlugin)
	if err != nil {
		return nil, err
	}
	name := entandoPlugin.Name
	if name == nil {
		return nil, fmt.Errorf("entandoPlugin.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandopluginsResource, c.ns, *name, types.ApplyPatchType, data), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeEntandoPlugins) ApplyStatus(ctx context.Context, entandoPlugin *entandoorgv1.EntandoPluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoPlugin, err error) {
	if entandoPlugin == nil {
		return nil, fmt.Errorf("entandoPlugin provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoPlugin)
	if err != nil {
		return nil, err
	}
	name := entandoPlugin.Name
	if name == nil {
		return nil, fmt.Errorf("entandoPlugin.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandopluginsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.EntandoPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoPlugin), err
}
