/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	entandoorgv1 "github.com/antromeo/entando-clients/pkg/client/applyconfiguration/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEntandoKeycloakServers implements EntandoKeycloakServerInterface
type FakeEntandoKeycloakServers struct {
	Fake *FakeEntandoV1
	ns   string
}

var entandokeycloakserversResource = v1.SchemeGroupVersion.WithResource("entandokeycloakservers")

var entandokeycloakserversKind = v1.SchemeGroupVersion.WithKind("EntandoKeycloakServer")

// Get takes name of the entandoKeycloakServer, and returns the corresponding entandoKeycloakServer object, and an error if there is any.
func (c *FakeEntandoKeycloakServers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EntandoKeycloakServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(entandokeycloakserversResource, c.ns, name), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// List takes label and field selectors, and returns the list of EntandoKeycloakServers that match those selectors.
func (c *FakeEntandoKeycloakServers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EntandoKeycloakServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(entandokeycloakserversResource, entandokeycloakserversKind, c.ns, opts), &v1.EntandoKeycloakServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EntandoKeycloakServerList{ListMeta: obj.(*v1.EntandoKeycloakServerList).ListMeta}
	for _, item := range obj.(*v1.EntandoKeycloakServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested entandoKeycloakServers.
func (c *FakeEntandoKeycloakServers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(entandokeycloakserversResource, c.ns, opts))

}

// Create takes the representation of a entandoKeycloakServer and creates it.  Returns the server's representation of the entandoKeycloakServer, and an error, if there is any.
func (c *FakeEntandoKeycloakServers) Create(ctx context.Context, entandoKeycloakServer *v1.EntandoKeycloakServer, opts metav1.CreateOptions) (result *v1.EntandoKeycloakServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(entandokeycloakserversResource, c.ns, entandoKeycloakServer), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// Update takes the representation of a entandoKeycloakServer and updates it. Returns the server's representation of the entandoKeycloakServer, and an error, if there is any.
func (c *FakeEntandoKeycloakServers) Update(ctx context.Context, entandoKeycloakServer *v1.EntandoKeycloakServer, opts metav1.UpdateOptions) (result *v1.EntandoKeycloakServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(entandokeycloakserversResource, c.ns, entandoKeycloakServer), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEntandoKeycloakServers) UpdateStatus(ctx context.Context, entandoKeycloakServer *v1.EntandoKeycloakServer, opts metav1.UpdateOptions) (*v1.EntandoKeycloakServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(entandokeycloakserversResource, "status", c.ns, entandoKeycloakServer), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// Delete takes name of the entandoKeycloakServer and deletes it. Returns an error if one occurs.
func (c *FakeEntandoKeycloakServers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(entandokeycloakserversResource, c.ns, name, opts), &v1.EntandoKeycloakServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEntandoKeycloakServers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(entandokeycloakserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EntandoKeycloakServerList{})
	return err
}

// Patch applies the patch and returns the patched entandoKeycloakServer.
func (c *FakeEntandoKeycloakServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EntandoKeycloakServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandokeycloakserversResource, c.ns, name, pt, data, subresources...), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied entandoKeycloakServer.
func (c *FakeEntandoKeycloakServers) Apply(ctx context.Context, entandoKeycloakServer *entandoorgv1.EntandoKeycloakServerApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoKeycloakServer, err error) {
	if entandoKeycloakServer == nil {
		return nil, fmt.Errorf("entandoKeycloakServer provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoKeycloakServer)
	if err != nil {
		return nil, err
	}
	name := entandoKeycloakServer.Name
	if name == nil {
		return nil, fmt.Errorf("entandoKeycloakServer.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandokeycloakserversResource, c.ns, *name, types.ApplyPatchType, data), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeEntandoKeycloakServers) ApplyStatus(ctx context.Context, entandoKeycloakServer *entandoorgv1.EntandoKeycloakServerApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EntandoKeycloakServer, err error) {
	if entandoKeycloakServer == nil {
		return nil, fmt.Errorf("entandoKeycloakServer provided to Apply must not be nil")
	}
	data, err := json.Marshal(entandoKeycloakServer)
	if err != nil {
		return nil, err
	}
	name := entandoKeycloakServer.Name
	if name == nil {
		return nil, fmt.Errorf("entandoKeycloakServer.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(entandokeycloakserversResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.EntandoKeycloakServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EntandoKeycloakServer), err
}
