/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	entandoorgv1 "github.com/antromeo/entando-clients/pkg/apis/entando.org/v1"
	versioned "github.com/antromeo/entando-clients/pkg/client/clientset/versioned"
	internalinterfaces "github.com/antromeo/entando-clients/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/antromeo/entando-clients/pkg/client/listers/entando.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EntandoAppPluginLinkInformer provides access to a shared informer and lister for
// EntandoAppPluginLinks.
type EntandoAppPluginLinkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EntandoAppPluginLinkLister
}

type entandoAppPluginLinkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEntandoAppPluginLinkInformer constructs a new informer for EntandoAppPluginLink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEntandoAppPluginLinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEntandoAppPluginLinkInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEntandoAppPluginLinkInformer constructs a new informer for EntandoAppPluginLink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEntandoAppPluginLinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EntandoV1().EntandoAppPluginLinks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EntandoV1().EntandoAppPluginLinks(namespace).Watch(context.TODO(), options)
			},
		},
		&entandoorgv1.EntandoAppPluginLink{},
		resyncPeriod,
		indexers,
	)
}

func (f *entandoAppPluginLinkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEntandoAppPluginLinkInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *entandoAppPluginLinkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&entandoorgv1.EntandoAppPluginLink{}, f.defaultInformer)
}

func (f *entandoAppPluginLinkInformer) Lister() v1.EntandoAppPluginLinkLister {
	return v1.NewEntandoAppPluginLinkLister(f.Informer().GetIndexer())
}
